- name: vault_demo
  hosts: localhost
  connection: local
  vars:
    message: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61393664326566313432396164373631633161326532333830333965346131323964386266613034
      6261393336386430613631643333666437663933633830310a663132353063626665386130313537
      39643430643432636533306663326265626566376436373466303762313037363532643137623536
      6465646164623036330a356134663835306439323764303539373436366536363366383039643339
      3465
  tasks:
    - name: print message
      ansible.builtin.debug:
        msg: "{{ message }}"